require 'io'

package.path = "./imgsize/?.lua;" .. package.path
local imgsize = require 'imagesize'

local file = {
	project_folder="."..package.config:sub(1,1)
}
file.__index = file

file.userskin_filenames = {
"approachcircle@2x.png","approachcircle@2x-{n}.png","approachcircle.png","approachcircle-{n}.png","button-left@2x.png","button-left@2x-{n}.png","button-left.png","button-left-{n}.png","button-middle@2x.png","button-middle@2x-{n}.png","button-middle.png","button-middle-{n}.png","button-right@2x.png","button-right@2x-{n}.png","button-right.png","button-right-{n}.png","comboburst@2x.png","comboburst@2x-{n}.png","comboburst.png","comboburst-{n}.png","count1@2x.png","count1@2x-{n}.png","count1.png","count1-{n}.png","count2@2x.png","count2@2x-{n}.png","count2.png","count2-{n}.png","count3@2x.png","count3@2x-{n}.png","count3.png","count3-{n}.png","cursor@2x.png","cursor@2x-{n}.png","cursormiddle@2x.png","cursormiddle@2x-{n}.png","cursormiddle.png","cursormiddle-{n}.png","cursor.png","cursor-{n}.png","cursor-smoke@2x.png","cursor-smoke@2x-{n}.png","cursor-smoke.png","cursor-smoke-{n}.png","cursortrail@2x.png","cursortrail@2x-{n}.png","cursortrail.png","cursortrail-{n}.png","default-0@2x.png","default-0@2x-{n}.png","default-0.png","default-0-{n}.png","default-1@2x.png","default-1@2x-{n}.png","default-1.png","default-1-{n}.png","default-2@2x.png","default-2@2x-{n}.png","default-2.png","default-2-{n}.png","default-3@2x.png","default-3@2x-{n}.png","default-3.png","default-3-{n}.png","default-4@2x.png","default-4@2x-{n}.png","default-4.png","default-4-{n}.png","default-5@2x.png","default-5@2x-{n}.png","default-5.png","default-5-{n}.png","default-6@2x.png","default-6@2x-{n}.png","default-6.png","default-6-{n}.png","default-7@2x.png","default-7@2x-{n}.png","default-7.png","default-7-{n}.png","default-8@2x.png","default-8@2x-{n}.png","default-8.png","default-8-{n}.png","default-9@2x.png","default-9@2x-{n}.png","default-9.png","default-9-{n}.png","fail-background.png","fail-background-{n}.png","followpoint@2x.png","followpoint@2x-{n}.png","followpoint.png","followpoint-{n}.png","fruit-apple@2x.png","fruit-apple@2x-{n}.png","fruit-apple-overlay@2x.png","fruit-apple-overlay@2x-{n}.png","fruit-apple-overlay.png","fruit-apple-overlay-{n}.png","fruit-apple.png","fruit-apple-{n}.png","fruit-bananas@2x.png","fruit-bananas@2x-{n}.png","fruit-bananas-overlay@2x.png","fruit-bananas-overlay@2x-{n}.png","fruit-bananas-overlay.png","fruit-bananas-overlay-{n}.png","fruit-bananas.png","fruit-bananas-{n}.png","fruit-catcher-fail@2x.png","fruit-catcher-fail@2x-{n}.png","fruit-catcher-fail.png","fruit-catcher-fail-{n}.png","fruit-catcher-idle@2x.png","fruit-catcher-idle@2x-{n}.png","fruit-catcher-idle.png","fruit-catcher-idle-{n}.png","fruit-catcher-kiai@2x.png","fruit-catcher-kiai@2x-{n}.png","fruit-catcher-kiai.png","fruit-catcher-kiai-{n}.png","fruit-drop@2x.png","fruit-drop@2x-{n}.png","fruit-drop.png","fruit-drop-{n}.png","fruit-grapes@2x.png","fruit-grapes@2x-{n}.png","fruit-grapes-overlay@2x.png","fruit-grapes-overlay@2x-{n}.png","fruit-grapes-overlay.png","fruit-grapes-overlay-{n}.png","fruit-grapes.png","fruit-grapes-{n}.png","fruit-orange@2x.png",
"fruit-orange@2x-{n}.png","fruit-orange-overlay@2x.png",
"fruit-orange-overlay@2x-{n}.png","fruit-orange-overlay.png","fruit-orange-overlay-{n}.png","fruit-orange.png","fruit-orange-{n}.png","fruit-pear@2x.png","fruit-pear@2x-{n}.png","fruit-pear-overlay@2x.png","fruit-pear-overlay@2x-{n}.png","fruit-pear-overlay.png","fruit-pear-overlay-{n}.png","fruit-pear.png","fruit-pear-{n}.png","fruit-ryuuta.png","fruit-ryuuta-{n}.png","go@2x.png","go@2x-{n}.png","go.png","go-{n}.png","hit0@2x.png","hit0@2x-{n}.png","hit0.png","hit0-{n}.png","hit100@2x.png","hit100@2x-{n}.png","hit100k@2x.png","hit100k@2x-{n}.png","hit100k.png","hit100k-{n}.png","hit100.png","hit100-{n}.png","hit300@2x.png","hit300@2x-{n}.png","hit300g@2x.png","hit300g@2x-{n}.png","hit300g.png","hit300g-{n}.png","hit300k@2x.png","hit300k@2x-{n}.png","hit300k.png","hit300k-{n}.png","hit300.png","hit300-{n}.png","hit50@2x.png","hit50@2x-{n}.png","hit50.png","hit50-{n}.png","hitcircle@2x.png","hitcircle@2x-{n}.png","hitcircleoverlay@2x.png","hitcircleoverlay@2x-{n}.png","hitcircleoverlay.png","hitcircleoverlay-{n}.png","hitcircle.png","hitcircle-{n}.png","hitcircleselect@2x.png","hitcircleselect@2x-{n}.png","hitcircleselect.png","hitcircleselect-{n}.png","inputoverlay-background@2x.png","inputoverlay-background@2x-{n}.png","inputoverlay-background.png","inputoverlay-background-{n}.png","inputoverlay-key@2x.png","inputoverlay-key@2x-{n}.png","inputoverlay-key.png","inputoverlay-key-{n}.png","lighting@2x.png","lighting@2x-{n}.png","lightingL-0@2x.png","lightingL-0@2x-{n}.png","lightingL-0.png","lightingL-0-{n}.png","lightingL-1@2x.png","lightingL-1@2x-{n}.png","lightingL-1.png","lightingL-1-{n}.png","lightingL-2@2x.png","lightingL-2@2x-{n}.png","lightingL-2.png","lightingL-2-{n}.png","lightingL-3@2x.png","lightingL-3@2x-{n}.png","lightingL-3.png","lightingL-3-{n}.png","lightingL-4@2x.png","lightingL-4@2x-{n}.png","lightingL-4.png","lightingL-4-{n}.png","lightingL-5@2x.png","lightingL-5@2x-{n}.png","lightingL-5.png","lightingL-5-{n}.png","lightingN@2x.png","lightingN@2x-{n}.png","lightingN.png","lightingN-{n}.png","lighting.png","lighting-{n}.png","mania-hit0@2x.png","mania-hit0@2x-{n}.png","mania-hit0.png","mania-hit0-{n}.png","mania-hit100@2x.png","mania-hit100@2x-{n}.png","mania-hit100.png","mania-hit100-{n}.png","mania-hit200@2x.png","mania-hit200@2x-{n}.png","mania-hit200.png","mania-hit200-{n}.png","mania-hit300@2x.png","mania-hit300@2x-{n}.png","mania-hit300g-0@2x.png","mania-hit300g-0@2x-{n}.png","mania-hit300g-0.png","mania-hit300g-0-{n}.png","mania-hit300g-1@2x.png","mania-hit300g-1@2x-{n}.png","mania-hit300g-1.png","mania-hit300g-1-{n}.png","mania-hit300.png","mania-hit300-{n}.png","mania-hit50@2x.png","mania-hit50@2x-{n}.png","mania-hit50.png","mania-hit50-{n}.png","mania-key1@2x.png","mania-key1@2x-{n}.png","mania-key1D@2x.png","mania-key1D@2x-{n}.png","mania-key1D.png","mania-key1D-{n}.png","mania-key1.png","mania-key1-{n}.png","mania-key2@2x.png","mania-key2@2x-{n}.png","mania-key2D@2x.png","mania-key2D@2x-{n}.png",
"mania-key2D.png","mania-key2D-{n}.png","mania-key2.png","mania-key2-{n}.png","mania-keyS@2x.png","mania-keyS@2x-{n}.png","mania-keySD@2x.png","mania-keySD@2x-{n}.png","mania-keySD.png","mania-keySD-{n}.png","mania-keyS.png","mania-keyS-{n}.png","mania-note1@2x.png","mania-note1@2x-{n}.png","mania-note1H@2x.png","mania-note1H@2x-{n}.png","mania-note1H.png","mania-note1H-{n}.png","mania-note1L-0@2x.png","mania-note1L-0@2x-{n}.png","mania-note1L-0.png","mania-note1L-0-{n}.png","mania-note1L-1@2x.png","mania-note1L-1@2x-{n}.png","mania-note1L-1.png","mania-note1L-1-{n}.png","mania-note1L-2@2x.png","mania-note1L-2@2x-{n}.png","mania-note1L-2.png","mania-note1L-2-{n}.png","mania-note1L-3@2x.png","mania-note1L-3@2x-{n}.png","mania-note1L-3.png","mania-note1L-3-{n}.png","mania-note1L-4@2x.png","mania-note1L-4@2x-{n}.png","mania-note1L-4.png","mania-note1L-4-{n}.png","mania-note1L-5@2x.png","mania-note1L-5@2x-{n}.png","mania-note1L-5.png","mania-note1L-5-{n}.png","mania-note1.png","mania-note1-{n}.png","mania-note2@2x.png","mania-note2@2x-{n}.png","mania-note2H@2x.png","mania-note2H@2x-{n}.png","mania-note2H.png","mania-note2H-{n}.png","mania-note2L-0@2x.png","mania-note2L-0@2x-{n}.png","mania-note2L-0.png","mania-note2L-0-{n}.png","mania-note2L-1@2x.png","mania-note2L-1@2x-{n}.png","mania-note2L-1.png","mania-note2L-1-{n}.png","mania-note2L-2@2x.png","mania-note2L-2@2x-{n}.png","mania-note2L-2.png","mania-note2L-2-{n}.png","mania-note2L-3@2x.png","mania-note2L-3@2x-{n}.png","mania-note2L-3.png","mania-note2L-3-{n}.png","mania-note2L-4@2x.png","mania-note2L-4@2x-{n}.png","mania-note2L-4.png","mania-note2L-4-{n}.png","mania-note2L-5@2x.png","mania-note2L-5@2x-{n}.png","mania-note2L-5.png","mania-note2L-5-{n}.png","mania-note2.png","mania-note2-{n}.png","mania-noteS@2x.png","mania-noteS@2x-{n}.png","mania-noteSH@2x.png","mania-noteSH@2x-{n}.png","mania-noteSH.png","mania-noteSH-{n}.png","mania-noteSL-0@2x.png","mania-noteSL-0@2x-{n}.png","mania-noteSL-0.png","mania-noteSL-0-{n}.png","mania-noteSL-1@2x.png","mania-noteSL-1@2x-{n}.png","mania-noteSL-1.png","mania-noteSL-1-{n}.png","mania-noteSL-2@2x.png","mania-noteSL-2@2x-{n}.png","mania-noteSL-2.png","mania-noteSL-2-{n}.png","mania-noteSL-3@2x.png","mania-noteSL-3@2x-{n}.png","mania-noteSL-3.png","mania-noteSL-3-{n}.png","mania-noteSL-4@2x.png","mania-noteSL-4@2x-{n}.png","mania-noteSL-4.png","mania-noteSL-4-{n}.png","mania-noteSL-5@2x.png","mania-noteSL-5@2x-{n}.png","mania-noteSL-5.png","mania-noteSL-5-{n}.png","mania-noteS.png","mania-noteS-{n}.png","mania-stage-hint@2x.png","mania-stage-hint@2x-{n}.png","mania-stage-hint.png","mania-stage-hint-{n}.png","mania-stage-left@2x.png","mania-stage-left@2x-{n}.png","mania-stage-left.png","mania-stage-left-{n}.png","mania-stage-light@2x.png","mania-stage-light@2x-{n}.png","mania-stage-light.png","mania-stage-light-{n}.png","mania-stage-right@2x.png","mania-stage-right@2x-{n}.png","mania-stage-right.png","mania-stage-right-{n}.png","menu-back@2x.png",
"menu-back@2x-{n}.png","menu-background@2x.png","menu-background@2x-{n}.png","menu-background.png","menu-background-{n}.png","menu-back.png","menu-back-{n}.png","menu-button-background@2x.png","menu-button-background@2x-{n}.png","menu-button-background.png","menu-button-background-{n}.png","mode-fruits@2x.png","mode-fruits@2x-{n}.png","mode-fruits-med@2x.png","mode-fruits-med@2x-{n}.png","mode-fruits-med.png","mode-fruits-med-{n}.png","mode-fruits.png","mode-fruits-{n}.png","mode-fruits-small@2x.png","mode-fruits-small@2x-{n}.png","mode-fruits-small.png","mode-fruits-small-{n}.png","mode-mania@2x.png","mode-mania@2x-{n}.png","mode-mania-med@2x.png","mode-mania-med@2x-{n}.png","mode-mania-med.png","mode-mania-med-{n}.png","mode-mania.png","mode-mania-{n}.png","mode-mania-small@2x.png","mode-mania-small@2x-{n}.png","mode-mania-small.png","mode-mania-small-{n}.png","mode-osu@2x.png","mode-osu@2x-{n}.png","mode-osu-med@2x.png","mode-osu-med@2x-{n}.png","mode-osu-med.png","mode-osu-med-{n}.png","mode-osu.png","mode-osu-{n}.png","mode-osu-small@2x.png","mode-osu-small@2x-{n}.png","mode-osu-small.png","mode-osu-small-{n}.png","mode-taiko@2x.png","mode-taiko@2x-{n}.png","mode-taiko-med@2x.png","mode-taiko-med@2x-{n}.png","mode-taiko-med.png","mode-taiko-med-{n}.png","mode-taiko.png","mode-taiko-{n}.png","mode-taiko-small@2x.png","mode-taiko-small@2x-{n}.png","mode-taiko-small.png","mode-taiko-small-{n}.png","particle100@2x.png","particle100@2x-{n}.png","particle100.png","particle100-{n}.png","particle300@2x.png","particle300@2x-{n}.png","particle300.png","particle300-{n}.png","particle50@2x.png","particle50@2x-{n}.png","particle50.png","particle50-{n}.png","pause-back@2x.png","pause-back@2x-{n}.png","pause-back.png","pause-back-{n}.png","pause-continue@2x.png","pause-continue@2x-{n}.png","pause-continue.png","pause-continue-{n}.png","pause-overlay.png","pause-overlay-{n}.png","pause-replay@2x.png","pause-replay@2x-{n}.png","pause-replay.png","pause-replay-{n}.png","pause-retry@2x.png","pause-retry@2x-{n}.png","pause-retry.png","pause-retry-{n}.png","pippidonclear.png","pippidonclear{n}.png","pippidonclear.png","pippidonfail{n}.png","pippidonfail.png","pippidonidle{n}.png","pippidonidle.png","pippidonkiai{n}.png","pippidonkiai.png","play-skip@2x.png","play-skip@2x-{n}.png","play-skip.png","play-skip-{n}.png","play-unranked@2x.png","play-unranked@2x-{n}.png","play-unranked.png","play-unranked-{n}.png","play-warningarrow@2x.png","play-warningarrow@2x-{n}.png","play-warningarrow.png","play-warningarrow-{n}.png","ranking-A@2x.png","ranking-A@2x-{n}.png","ranking-accuracy@2x.png","ranking-accuracy@2x-{n}.png","ranking-accuracy.png","ranking-accuracy-{n}.png","ranking-A.png","ranking-A-{n}.png","ranking-A-small@2x.png","ranking-A-small@2x-{n}.png","ranking-A-small.png","ranking-A-small-{n}.png","ranking-B@2x.png","ranking-B@2x-{n}.png","ranking-B.png","ranking-B-{n}.png","ranking-B-small@2x.png","ranking-B-small@2x-{n}.png","ranking-B-small.png",
"ranking-B-small-{n}.png","ranking-C@2x.png","ranking-C@2x-{n}.png","ranking-C.png","ranking-C-{n}.png","ranking-C-small@2x.png","ranking-C-small@2x-{n}.png","ranking-C-small.png","ranking-C-small-{n}.png","ranking-D@2x.png","ranking-D@2x-{n}.png","ranking-D.png","ranking-D-{n}.png","ranking-D-small@2x.png","ranking-D-small@2x-{n}.png","ranking-D-small.png","ranking-D-small-{n}.png","ranking-graph@2x.png","ranking-graph@2x-{n}.png","ranking-graph.png","ranking-graph-{n}.png","ranking-maxcombo@2x.png","ranking-maxcombo@2x-{n}.png","ranking-maxcombo.png","ranking-maxcombo-{n}.png","ranking-panel@2x.png","ranking-panel@2x-{n}.png","ranking-panel.png","ranking-panel-{n}.png","ranking-perfect@2x.png","ranking-perfect@2x-{n}.png","ranking-perfect.png","ranking-perfect-{n}.png","ranking-S@2x.png","ranking-S@2x-{n}.png","ranking-SH@2x.png","ranking-SH@2x-{n}.png","ranking-SH.png","ranking-SH-{n}.png","ranking-SH-small@2x.png","ranking-SH-small@2x-{n}.png","ranking-SH-small.png","ranking-SH-small-{n}.png","ranking-S.png","ranking-S-{n}.png","ranking-S-small@2x.png","ranking-S-small@2x-{n}.png","ranking-S-small.png","ranking-S-small-{n}.png","ranking-title@2x.png","ranking-title@2x-{n}.png","ranking-title.png","ranking-title-{n}.png","ranking-X@2x.png","ranking-X@2x-{n}.png","ranking-XH@2x.png","ranking-XH@2x-{n}.png","ranking-XH.png","ranking-XH-{n}.png","ranking-XH-small@2x.png","ranking-XH-small@2x-{n}.png","ranking-XH-small.png","ranking-XH-small-{n}.png","ranking-X.png","ranking-X-{n}.png","ranking-X-small@2x.png","ranking-X-small@2x-{n}.png","ranking-X-small.png","ranking-X-small-{n}.png","ready@2x.png","ready@2x-{n}.png","ready.png","ready-{n}.png","reversearrow@2x.png","reversearrow@2x-{n}.png","reversearrow.png","reversearrow-{n}.png","score-0@2x.png","score-0@2x-{n}.png","score-0.png","score-0-{n}.png","score-1@2x.png","score-1@2x-{n}.png","score-1.png","score-1-{n}.png","score-2@2x.png","score-2@2x-{n}.png","score-2.png","score-2-{n}.png","score-3@2x.png","score-3@2x-{n}.png","score-3.png","score-3-{n}.png","score-4@2x.png","score-4@2x-{n}.png","score-4.png","score-4-{n}.png","score-5@2x.png","score-5@2x-{n}.png","score-5.png","score-5-{n}.png","score-6@2x.png","score-6@2x-{n}.png","score-6.png","score-6-{n}.png","score-7@2x.png","score-7@2x-{n}.png","score-7.png","score-7-{n}.png","score-8@2x.png","score-8@2x-{n}.png","score-8.png","score-8-{n}.png","score-9@2x.png","score-9@2x-{n}.png","score-9.png","score-9-{n}.png","scorebar-bg@2x.png","scorebar-bg@2x-{n}.png","scorebar-bg.png","scorebar-bg-{n}.png","scorebar-colour@2x.png","scorebar-colour@2x-{n}.png","scorebar-colour.png","scorebar-colour-{n}.png","scorebar-marker@2x.png","scorebar-marker@2x-{n}.png","scorebar-marker.png","scorebar-marker-{n}.png","scoreboard-explosion-1@2x.png","scoreboard-explosion-1@2x-{n}.png","scoreboard-explosion-1.png","scoreboard-explosion-1-{n}.png","scoreboard-explosion-2@2x.png","scoreboard-explosion-2@2x-{n}.png","scoreboard-explosion-2.png",
"scoreboard-explosion-2-{n}.png","score-comma@2x.png","score-comma@2x-{n}.png","score-comma.png","score-comma-{n}.png","score-dot@2x.png","score-dot@2x-{n}.png","score-dot.png","score-dot-{n}.png","score-percent@2x.png","score-percent@2x-{n}.png","score-percent.png","score-percent-{n}.png","score-x@2x.png","score-x@2x-{n}.png","score-x.png","score-x-{n}.png","section-fail@2x.png","section-fail@2x-{n}.png","section-fail.png","section-fail-{n}.png","section-pass@2x.png","section-pass@2x-{n}.png","section-pass.png","section-pass-{n}.png","selection-mod-autoplay@2x.png","selection-mod-autoplay@2x-{n}.png","selection-mod-autoplay.png","selection-mod-autoplay-{n}.png","selection-mod-cinema@2x.png","selection-mod-cinema@2x-{n}.png","selection-mod-cinema.png","selection-mod-cinema-{n}.png","selection-mod-doubletime@2x.png","selection-mod-doubletime@2x-{n}.png","selection-mod-doubletime.png","selection-mod-doubletime-{n}.png","selection-mode@2x.png","selection-mode@2x-{n}.png","selection-mod-easy@2x.png","selection-mod-easy@2x-{n}.png","selection-mod-easy.png","selection-mod-easy-{n}.png","selection-mode-over@2x.png","selection-mode-over@2x-{n}.png","selection-mode-over.png","selection-mode-over-{n}.png","selection-mode.png","selection-mode-{n}.png","selection-mod-fadein@2x.png","selection-mod-fadein@2x-{n}.png","selection-mod-fadein.png","selection-mod-fadein-{n}.png","selection-mod-flashlight@2x.png","selection-mod-flashlight@2x-{n}.png","selection-mod-flashlight.png","selection-mod-flashlight-{n}.png","selection-mod-halftime@2x.png","selection-mod-halftime@2x-{n}.png","selection-mod-halftime.png","selection-mod-halftime-{n}.png","selection-mod-hardrock@2x.png","selection-mod-hardrock@2x-{n}.png","selection-mod-hardrock.png","selection-mod-hardrock-{n}.png","selection-mod-hidden@2x.png","selection-mod-hidden@2x-{n}.png","selection-mod-hidden.png","selection-mod-hidden-{n}.png","selection-mod-key1@2x.png","selection-mod-key1@2x-{n}.png","selection-mod-key1.png","selection-mod-key1-{n}.png","selection-mod-key2@2x.png","selection-mod-key2@2x-{n}.png","selection-mod-key2.png","selection-mod-key2-{n}.png","selection-mod-key2.png.png","selection-mod-key2-{n}.png.png","selection-mod-key3@2x.png","selection-mod-key3@2x-{n}.png","selection-mod-key3.png","selection-mod-key3-{n}.png","selection-mod-key3.png.png","selection-mod-key3-{n}.png.png","selection-mod-key4@2x.png","selection-mod-key4@2x-{n}.png","selection-mod-key4.png","selection-mod-key4-{n}.png","selection-mod-key5@2x.png","selection-mod-key5@2x-{n}.png","selection-mod-key5.png","selection-mod-key5-{n}.png","selection-mod-key6@2x.png","selection-mod-key6@2x-{n}.png","selection-mod-key6.png","selection-mod-key6-{n}.png","selection-mod-key7@2x.png","selection-mod-key7@2x-{n}.png","selection-mod-key7.png","selection-mod-key7-{n}.png","selection-mod-key8@2x.png","selection-mod-key8@2x-{n}.png","selection-mod-key8.png","selection-mod-key8-{n}.png","selection-mod-key9@2x.png","selection-mod-key9@2x-{n}.png",
"selection-mod-key9.png","selection-mod-key9-{n}.png","selection-mod-key9.png.png","selection-mod-key9-{n}.png.png","selection-mod-nightcore@2x.png","selection-mod-nightcore@2x-{n}.png","selection-mod-nightcore.png","selection-mod-nightcore-{n}.png","selection-mod-nofail@2x.png","selection-mod-nofail@2x-{n}.png","selection-mod-nofail.png","selection-mod-nofail-{n}.png","selection-mod-perfect@2x.png","selection-mod-perfect@2x-{n}.png","selection-mod-perfect.png","selection-mod-perfect-{n}.png","selection-mod-random@2x.png","selection-mod-random@2x-{n}.png","selection-mod-random.png","selection-mod-random-{n}.png","selection-mod-relax2@2x.png","selection-mod-relax2@2x-{n}.png","selection-mod-relax2.png","selection-mod-relax2-{n}.png","selection-mod-relax@2x.png","selection-mod-relax@2x-{n}.png","selection-mod-relax.png","selection-mod-relax-{n}.png","selection-mods@2x.png","selection-mods@2x-{n}.png","selection-mods-over@2x.png","selection-mods-over@2x-{n}.png","selection-mods-over.png","selection-mods-over-{n}.png","selection-mods.png","selection-mods-{n}.png","selection-mod-spunout@2x.png","selection-mod-spunout@2x-{n}.png","selection-mod-spunout.png","selection-mod-spunout-{n}.png","selection-mod-suddendeath@2x.png","selection-mod-suddendeath@2x-{n}.png","selection-mod-suddendeath.png","selection-mod-suddendeath-{n}.png","selection-mod-target@2x.png","selection-mod-target@2x-{n}.png","selection-mod-target.png","selection-mod-target-{n}.png","selection-options@2x.png","selection-options@2x-{n}.png","selection-options-over@2x.png","selection-options-over@2x-{n}.png","selection-options-over.png","selection-options-over-{n}.png","selection-options.png","selection-options-{n}.png","selection-random@2x.png","selection-random@2x-{n}.png","selection-random-over@2x.png","selection-random-over@2x-{n}.png","selection-random-over.png","selection-random-over-{n}.png","selection-random.png","selection-random-{n}.png","sliderb0@2x.png","sliderb0@2x-{n}.png","sliderb0.png","sliderb0-{n}.png","sliderb1@2x.png","sliderb1@2x-{n}.png","sliderb1.png","sliderb1-{n}.png","sliderb2@2x.png","sliderb2@2x-{n}.png","sliderb2.png","sliderb2-{n}.png","sliderb3@2x.png","sliderb3@2x-{n}.png","sliderb3.png","sliderb3-{n}.png","sliderb4@2x.png","sliderb4@2x-{n}.png","sliderb4.png","sliderb4-{n}.png","sliderb5@2x.png","sliderb5@2x-{n}.png","sliderb5.png","sliderb5-{n}.png","sliderb6@2x.png","sliderb6@2x-{n}.png","sliderb6.png","sliderb6-{n}.png","sliderb7@2x.png","sliderb7@2x-{n}.png","sliderb7.png","sliderb7-{n}.png","sliderb8@2x.png","sliderb8@2x-{n}.png","sliderb8.png","sliderb8-{n}.png","sliderb9@2x.png","sliderb9@2x-{n}.png","sliderb9.png","sliderb9-{n}.png","sliderb-nd@2x.png","sliderb-nd@2x-{n}.png","sliderb-nd.png","sliderb-nd-{n}.png","sliderb-spec@2x.png","sliderb-spec@2x-{n}.png","sliderb-spec.png","sliderb-spec-{n}.png","sliderfollowcircle@2x.png","sliderfollowcircle@2x-{n}.png","sliderfollowcircle.png","sliderfollowcircle-{n}.png","sliderscorepoint@2x.png",
"sliderscorepoint@2x-{n}.png","sliderscorepoint.png","sliderscorepoint-{n}.png","spinner-approachcircle.png","spinner-approachcircle-{n}.png","spinner-bottom@2x.png","spinner-bottom@2x-{n}.png","spinner-bottom.png","spinner-bottom-{n}.png","spinner-clear@2x.png","spinner-clear@2x-{n}.png","spinner-clear.png","spinner-clear-{n}.png","spinner-glow@2x.png","spinner-glow@2x-{n}.png","spinner-glow.png","spinner-glow-{n}.png","spinner-middle2@2x.png","spinner-middle2@2x-{n}.png","spinner-middle2.png","spinner-middle2-{n}.png","spinner-middle@2x.png","spinner-middle@2x-{n}.png","spinner-middle.png","spinner-middle-{n}.png","spinner-rpm@2x.png","spinner-rpm@2x-{n}.png","spinner-rpm.png","spinner-rpm-{n}.png","spinner-spin@2x.png","spinner-spin@2x-{n}.png","spinner-spin.png","spinner-spin-{n}.png","spinner-top@2x.png","spinner-top@2x-{n}.png","spinner-top.png","spinner-top-{n}.png","star2@2x.png","star2@2x-{n}.png","star2.png","star2-{n}.png","star@2x.png","star@2x-{n}.png","star.png","star-{n}.png","taiko-bar-right-glow.png","taiko-bar-right-glow-{n}.png","taiko-bar-right.png","taiko-bar-right-{n}.png","taikobigcircle@2x.png","taikobigcircle@2x-{n}.png","taikobigcircleoverlay@2x.png","taikobigcircleoverlay@2x-{n}.png","taikobigcircleoverlay.png","taikobigcircleoverlay-{n}.png","taikobigcircle.png","taikobigcircle-{n}.png","taiko-flower-group.png","taiko-flower-group-{n}.png","taiko-flower-group@x2.png","taiko-flower-group@x2-{n}.png","taiko-hit0@2x.png","taiko-hit0@2x-{n}.png","taiko-hit0.png","taiko-hit0-{n}.png","taiko-hit100@2x.png","taiko-hit100@2x-{n}.png","taiko-hit100k@2x.png","taiko-hit100k@2x-{n}.png","taiko-hit100k.png","taiko-hit100k-{n}.png","taiko-hit100.png","taiko-hit100-{n}.png","taiko-hit300@2x.png","taiko-hit300@2x-{n}.png","taiko-hit300g@2x.png","taiko-hit300g@2x-{n}.png","taiko-hit300g.png","taiko-hit300g-{n}.png","taiko-hit300k@2x.png","taiko-hit300k@2x-{n}.png","taiko-hit300k.png","taiko-hit300k-{n}.png","taiko-hit300.png","taiko-hit300-{n}.png","taikohitcircle@2x.png","taikohitcircle@2x-{n}.png","taikohitcircleoverlay@2x.png","taikohitcircleoverlay@2x-{n}.png","taikohitcircleoverlay.png","taikohitcircleoverlay-{n}.png","taikohitcircle.png","taikohitcircle-{n}.png","taiko-roll-end@2x.png","taiko-roll-end@2x-{n}.png","taiko-roll-end.png","taiko-roll-end-{n}.png","taiko-roll-middle@2x.png","taiko-roll-middle@2x-{n}.png","taiko-roll-middle.png","taiko-roll-middle-{n}.png","taiko-Slider@2x.png","taiko-Slider@2x-{n}.png","taiko-Slider-fail@2x.png","taiko-Slider-fail@2x-{n}.png","taiko-Slider-fail.png","taiko-Slider-fail-{n}.png","taiko-Slider.png","taiko-Slider-{n}.png","lightingL.png",
"lightingL-{n}.png",
"applause.wav","check-off.wav","check-on.wav","click-close.wav","click-short-confirm.wav","click-short.wav","combobreak.wav","count.wav","drum-hitclap.wav","drum-hitfinish.wav","drum-hitnormal.wav","drum-hitwhistle.wav","drum-sliderslide.wav","drum-slidertick.wav","drum-sliderwhistle.wav","gos.wav","heartbeat.wav","key-confirm.wav","key-delete.wav","key-movement.wav","key-press-1.wav","key-press-2.wav","key-press-3.wav","key-press-4.wav","match-confirm.wav","match-join.wav","match-leave.wav","match-notready.wav","match-ready.wav","match-start.wav","menu-back-click.wav","menuback.wav","menu-charts-click.wav","menuclick.wav","menu-direct-click.wav","menu-exit-click.wav","menu-freeplay-click.wav","menuhit.wav","menu-multiplayer-click.wav","menu-options-click.wav","menu-play-click.wav","metronomelow.wav","nightcore-clap.wav","nightcore-finish.wav","nightcore-hat.wav","nightcore-kick.wav","normal-hitclap.wav","normal-hitfinish.wav","normal-hitnormal.wav","normal-hitwhistle.wav","normal-sliderslide.wav","normal-slidertick.wav","normal-sliderwhistle.wav","pause-back-click.wav","pause-continue-click.wav","pause-hover.wav","pause-retry-click.wav","readys.wav","sectionfail.wav","sectionpass.wav","seeya.wav","select-difficulty.wav","select-expand.wav","shutter.wav","sliderbar.wav","soft-hitclap.wav","soft-hitfinish.wav","soft-hitnormal.wav","soft-hitwhistle.wav","soft-sliderslide.wav","soft-slidertick.wav","soft-sliderwhistle.wav","spinnerbonus.wav","spinnerspin.wav","taiko-normal-hitclap.wav","taiko-normal-hitfinish.wav","taiko-normal-hitnormal.wav","taiko-normal-hitwhistle.wav","taiko-soft-hitclap.wav","taiko-soft-hitfinish.wav","taiko-soft-hitnormal.wav","taiko-soft-hitwhistle.wav","welcome.wav"
}

function file:setProjectFolder(f)
	if type(f)~="string" then sb_log:error("file:setProjectFolder(): string required") end
	self.project_folder = f
end

-- animated_file -- boolean if animated file (eg if img.png, then img0.png is tested
--                                            when determining if file exists).
--                  
function file:new(filename, animated_file)
	assert(type(filename)=="string","file:new(filename): string expected.")

	local t = {
		filename = filename,
		w=0,
		h=0,
		userskin=file:isFilenameUserskin(filename),
		filetype = file:getFilenameType(filename),
		file_error=nil,
		file_error_num=nil,

		_absfpath=nil
	}

	local absfpath = self.project_folder..filename
	if animated_file then
		local period_i = filename:find("%.[^%.]*$")
		absfpath = self.project_folder..filename:sub(1,period_i-1).."0"..filename:sub(period_i,-1)
		t._absfpath=absfpath
	end

	local fr,fr_error,fr_error_num = io.open(absfpath,"r")
	if fr then
		if t.filetype=="image" and not t.userskin then
			local width, height, format = imgsize.imgsize(fr)
			t.w=width
			t.h=height
		end
		fr:close()
	else
		t.file_error     = fr_error
		t.file_error_num = fr_error_num
	end

	setmetatable(t, file)
	return t
end

function file:isFilenameUserskin(f)
	f = f or self.filename

	for i,v in ipairs(self.userskin_filenames) do
		if f==v then
			return true
		end

		local sub_n_i, sub_n_j = v:find("{n}")
		if sub_n_i then
			local match_pre  = f:sub(1,sub_n_i-1) == v:sub(1,sub_n_i-1) 

			if match_pre then
				local post_i,post_j = f:sub(sub_n_i,-1):find("%D+")
				local match_post = f:sub(sub_n_i+post_i-1,-1) == v:sub(sub_n_j+1,-1)

				if match_post and f:sub(sub_n_i,sub_n_i+post_i-2):match("^%d+$") then
					return true
				end
			end
		end
	end

	return false
end

function file:getFilenameType(f)
	f = f or self.filename

	local ff = string.lower(f)

	if f:match(".png$") then return "image" end
	if f:match(".jpg$") then return "image" end
	if f:match(".wav$") then return "audio" end
	if f:match(".mp3$") then return "audio" end
	if f:match(".ogg$") then return "audio" end
	return "unknown"
end


function file:out()
	return self.filename
end

return file
